version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
      - DB_NAME=master
      - DB_USER=sa
      - DB_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P YourStrong!Passw0rd -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend
    volumes:
      - ./migrations/init.sql:/init.sql
    command: >
      bash -c "
        /opt/mssql/bin/sqlservr &
        echo 'Waiting for SQL Server to start...'
        sleep 30
        /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrong!Passw0rd -d master -i /init.sql
        echo 'Database setup completed successfully'
        wait
      "

  node-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-api
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    environment:
      - DB_HOST=sqlserver
      - DB_USER=sa
      - DB_PASSWORD=YourStrong!Passw0rd
      - DB_NAME=master
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - backend
    mem_limit: 256m
    cpus: 0.2

networks:
  backend:
    driver: bridge